Repository Hyundai-IT-E-7th-10Team/Gather-E, pull requests merged in 2023-07, with the labels that each got.

#43 [230701] 스플래시 화면 적용
  gather-e_android/app/build.gradle
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/CircleProgressDialog.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/LoginActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/SplashActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringRetrofitProvider.kt
  gather-e_android/app/src/main/res/drawable/loading_spinner.xml
  gather-e_android/app/src/main/res/drawable/logo_rex.png
  gather-e_android/app/src/main/res/layout/fragment_circle_progress_dialog.xml
  gather-e_android/app/src/main/res/values/themes.xml
Labels: 로그인, 로그인 페이지

#44 [230701] Notification 세팅
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/BottomNavigationVarActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/firebase/FirebaseMessagingService.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/firebase/NotificationType.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
Labels: 알림

#47 [230701] 현재 유저 정보 API
  gather-e_android/app/src/main/java/com/kosa/gather_e/LoginActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/SplashActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/user/CurrUser.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/mypage/MypageFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/mypage/MypageViewModel.kt
Labels: 유저

#52 [230701] location이랑 날짜 포맷팅
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/gather/GatherEntity.kt
Labels: 글작성

#54 [230702] 홈 화면 리스트 불러오기
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/gather/GatherEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/gather/GatherInfo.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/user/UserEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeRecyclerViewAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeViewModel.kt
  gather-e_android/app/src/main/res/drawable/round_board.xml
  gather-e_android/app/src/main/res/layout/fragment_home.xml
  gather-e_android/app/src/main/res/layout/home_card.xml
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/vo/GatherVO.java
  gather-e_spring/src/main/resources/mapper/GatherMapper.xml
Labels: 모임리스트

#56 [230702] Chat Bug Resolve & FCM API Test
  gather-e_android/app/src/main/java/com/kosa/gather_e/SplashActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/notification/PushNotificationEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/user/CurrUser.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/firebase/FCMRetrofitProvider.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/firebase/FirebaseMessagingService.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/firebase/NotificationInterface.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/firebase/NotificationType.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListAdapter.kt
Labels: 채팅방, 알림, FCM

#58 [230702] [spring] getCurrentRecruit
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/map/CurrentRecruitGatherEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringInterface.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringRetrofitProvider.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapFragment.kt
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_11_swimmig.xml
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_1_football.xml
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_4_basketball.xml
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_7_volleyball.xml
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_8_bowling.xml
  gather-e_spring/src/main/java/com/kosa/gather_e/map_gather/controller/MapGatherController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/map_gather/vo/CurrentRecruitGatherVO.java
  gather-e_spring/src/main/resources/mapper/MapGatherMapper.xml
Labels: 지도-현재모집중인모임

#59 [230702] 홈화면 조건 정렬 추가
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/gather/GatherEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/gather/GatherInfo.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeRecyclerViewAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeViewModel.kt
  gather-e_android/app/src/main/res/drawable/round_button.xml
  gather-e_android/app/src/main/res/layout/fragment_home.xml
  gather-e_android/app/src/main/res/layout/home_card.xml
  gather-e_android/app/src/main/res/values/themes.xml
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/service/KakaoAuthService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/vo/GatherVO.java
  gather-e_spring/src/main/resources/mapper/GatherMapper.xml
Labels: 모임글, 모임리스트

#62 [230703] 현재 모집 중인 모임 조건 2개를 getGather에서 가져와서 필터링하도록
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/user/CurrUser.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapCurrentRecruiteFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapPastMeetingFragment.kt
  gather-e_android/app/src/main/res/anim/slide_in_up.xml
  gather-e_android/app/src/main/res/anim/slide_out_up.xml
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_locationbutton.png
  gather-e_android/app/src/main/res/drawable/circle_background.xml
  gather-e_android/app/src/main/res/layout/fragment_map_current_recruite.xml
  gather-e_android/app/src/main/res/layout/fragment_map_past_meeting.xml
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/vo/GatherVO.java
Labels: 지도-현재모집중인모임

#65 [230703] getPastMeeting Spring API
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/map/PastMeetingGatherEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringInterface.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapCurrentRecruiteFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapPastMeetingFragment.kt
  gather-e_spring/src/main/java/com/kosa/gather_e/map_gather/controller/MapGatherController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/map_gather/dao/MapGatherDAO.java
  gather-e_spring/src/main/java/com/kosa/gather_e/map_gather/service/MapGatherService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/map_gather/service/MapGatherServiceImpl.java
  gather-e_spring/src/main/java/com/kosa/gather_e/map_gather/vo/PastMeetingGatherVO.java
  gather-e_spring/src/main/resources/mapper/MapGatherMapper.xml
Labels: 지도-내가참여했던모임

#66 [230703] 채팅방 유저들에게 알림 보내기 기능
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/chat/ChatListItem.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListFragment.kt
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/fragment_chat_list.xml
Labels: 채팅방, 알림, FCM

#68 [230703] design icon 색깔 바꾸기
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p10_pingpong.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p11_swimmig.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p12_riding.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p13_skate.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p14_cycling.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p15_yoga.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p16_pilates.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p17_climbing.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p18_billiard.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p19_dancing.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p1_football.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p20_boxing.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p2_tennis.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p3_golf.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p4_basketball.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p5_hiking.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p6_shuttlecock.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p7_volleyball.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p8_bowling.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/ic_p9_squash.png
Labels: 지도-내가참여했던모임

#71 [230703] 상세 보기 기능 추가
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/LoginActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/SplashActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/gather/GatherEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/user/CurrUser.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/user/JwtToken.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/user/UserEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringInterface.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeRecyclerViewAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/PostDetailActivity.kt
  gather-e_android/app/src/main/res/drawable/ic_crown.png
  gather-e_android/app/src/main/res/layout/activity_post_detail.xml
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/controller/AuthController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/dto/Token.java
Labels: 디테일

#72 [230704] Scroll Bottom & Image Loading Fix -hsh
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/item_chat_mine.xml
Labels: 채팅방, 이미지 전송

#77 [230704] 상세 페이지 작성
  gather-e_android/app/src/main/java/com/kosa/gather_e/LoginActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/SplashActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/user_gather/UserGather.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringInterface.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeRecyclerViewAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeViewModel.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/PostDetailActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/mypage/MypageViewModel.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/util/CurrUser.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/util/GatherUtil.kt
  gather-e_android/app/src/main/res/layout/activity_post_detail.xml
  gather-e_android/app/src/main/res/values/colors.xml
  gather-e_spring/src/main/java/com/kosa/gather_e/user_gather/controller/UserGatherController.java
Labels: 디테일

#79 feat : [ChatRoom] Coroutine 처리 - hsh
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/chat/ChatListItem.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/notification/PushNotificationEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/firebase/FirebaseMessagingService.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListFragment.kt
  gather-e_android/app/src/main/res/drawable/send.png
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/item_chat_list.xml
  gather-e_android/app/src/main/res/layout/item_chat_mine.xml
  gather-e_android/app/src/main/res/layout/item_chat_your.xml
Labels: 채팅방, coroutine

#81 [230704] 홈화면 버그 수정
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringInterface.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeRecyclerViewAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/HomeViewModel.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/PostDetailActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapAllGatherFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapRecruitedByMeFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/util/Categories.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/util/GatherUtil.kt
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/controller/GatherController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/dao/GatherDAO.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/service/GatherService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/user_gather/controller/UserGatherController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/user_gather/service/UserGatherServiceImpl.java
  gather-e_spring/src/main/resources/application.yml
  gather-e_spring/src/main/resources/mapper/GatherMapper.xml
Labels: bug, 모임글, 모임리스트, 디테일

#86 feat : [Image Download] -hsh
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/res/drawable/ic_location.xml
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/item_chat_mine.xml
  gather-e_android/app/src/main/res/layout/item_chat_your.xml
Labels: 채팅방, 이미지 다운

#90 [230705] 디테일 페이지 버그 수정
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/PostDetailActivity.kt
Labels: bug, 디테일

#91 [230705] ChatRoom UI
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/res/drawable/round_background.xml
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/item_chat_mine.xml
  gather-e_android/app/src/main/res/layout/item_chat_your.xml
Labels: 채팅방, 디자인, 디테일

#93 [230705] 지도 UI 수정
  gather-e_android/app/src/main/res/drawable/background_map_button.xml
  gather-e_android/app/src/main/res/drawable/ic_circle.xml
  gather-e_android/app/src/main/res/drawable/map_button_background.xml
  gather-e_android/app/src/main/res/font/app_font.xml
  gather-e_android/app/src/main/res/font/cutefont.ttf
  gather-e_android/app/src/main/res/font/gmarketsansbold.otf
  gather-e_android/app/src/main/res/font/gmarketsanslight.otf
  gather-e_android/app/src/main/res/font/gmarketsansmedium.otf
  gather-e_android/app/src/main/res/font/jalnan.ttf
  gather-e_android/app/src/main/res/layout/activity_bottom_navigation_var.xml
  gather-e_android/app/src/main/res/layout/fragment_home.xml
  gather-e_android/app/src/main/res/layout/fragment_map.xml
  gather-e_android/app/src/main/res/layout/fragment_mypage.xml
  gather-e_android/app/src/main/res/layout/item_chat_list.xml
  gather-e_android/app/src/main/res/layout/toolbar_map.xml
  gather-e_android/app/src/main/res/menu/bottom_nav_menu.xml
  gather-e_android/app/src/main/res/values/colors.xml
  gather-e_android/app/src/main/res/values/style.xml
  gather-e_android/app/src/main/res/values/themes.xml
Labels: 디자인, 디테일

#96 [230705] UI 개선
  gather-e_android/app/build.gradle
  gather-e_android/app/src/main/res/drawable-xxxhdpi/kakao_login_large_narrow.png
  gather-e_android/app/src/main/res/drawable-xxxhdpi/loading_spinner.xml
  gather-e_android/app/src/main/res/drawable-xxxhdpi/logo_rec.png
  gather-e_android/app/src/main/res/drawable/gather_e_min.xml
  gather-e_android/app/src/main/res/drawable/kakao_login_large_wide.png
  gather-e_android/app/src/main/res/drawable/splash_logo.xml
  gather-e_android/app/src/main/res/layout/activity_login.xml
  gather-e_android/app/src/main/res/layout/activity_post_detail.xml
  gather-e_android/app/src/main/res/layout/home_card.xml
  gather-e_android/app/src/main/res/values/themes.xml
Labels: 모임글, 디자인, 디테일

#101 feat : [Notification] 알림 기능 추가 - hsh
  gather-e_android/app/build.gradle
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/firebase/FirebaseMessagingService.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/PostDetailActivity.kt
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/item_chat_list.xml
Labels: 알림, FCM

#104 [230706] 소셜 로그인 추가
  gather-e_android/app/build.gradle
  gather-e_android/app/src/main/java/com/kosa/gather_e/LoginActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/SplashActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringInterface.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/mypage/MypageFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/util/LoginUtil.kt
  gather-e_android/app/src/main/res/layout/activity_login.xml
  gather-e_spring/build.gradle
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/controller/AuthController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/service/GoogleAuthService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/service/KakaoAuthService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/service/KakaoClient.java
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/service/Provider.java
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/service/UserService.java
Labels: 로그인, 로그인 페이지

#109 feat : [ChatRoom] 광고 아이템 추가 - hsh
  gather-e_android/app/build.gradle
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/chat/HmallItem.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/firebase/FCMRetrofitProvider.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ImageAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/home/PostDetailActivity.kt
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/item_hmall.xml
Labels: 크롤링
