Repository Hyundai-IT-E-7th-10Team/Gather-E, pull requests merged in 2023-06, with the labels that each got.

#8 feat: [모임 이미지 CRUD] Spring boot Rest API - hsh
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/controller/GatherController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/dao/GatherDAO.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/service/GatherImgService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/service/GatherImgServiceImpl.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/service/GatherService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/service/GatherServiceImpl.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/vo/GatherImgVO.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/vo/GatherVO.java
  gather-e_spring/src/main/resources/mapper/GatherMapper.xml
Labels: 모임글

#10 [230627] 장소 리스트 검색
  gather-e_android/app/build.gradle
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/LocationApiResponse.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/SearchLocationActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/SearchLocationApiService.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/data/model/SearchLocationEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/data/repository/searchLocation/SearchLocationAPIService.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/data/repository/searchLocation/SearchLocationDataSource.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/data/repository/searchLocation/SearchLocationRepository.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/map/MapFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/searchlocation/SearchLocationActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/searchlocation/SearchLocationAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/searchlocation/SearchLocationViewModel.kt
  gather-e_android/app/src/main/res/layout/activity_search_location.xml
  gather-e_android/app/src/main/res/layout/activity_write.xml
  gather-e_android/app/src/main/res/layout/fragment_map.xml
  gather-e_android/app/src/main/res/layout/item_location_list.xml
Labels: 글작성, 장소 검색 기능

#12 feat: [ChatListFragment] 채팅방 리스트 구현 - hsh
  gather-e_android/.gitignore
  gather-e_android/app/build.gradle
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/DBKey.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/data/model/chat/ChatItem.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/data/model/chat/ChatListItem.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListViewModel.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/list/ListFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/list/ListViewModel.kt
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/fragment_chat_list.xml
  gather-e_android/app/src/main/res/layout/fragment_list.xml
  gather-e_android/app/src/main/res/layout/item_chat.xml
  gather-e_android/app/src/main/res/layout/item_chat_list.xml
  gather-e_android/app/src/main/res/navigation/mobile_navigation.xml
  gather-e_android/build.gradle
Labels: 채팅방리스트

#14 [230628] 주소, 모집인원 작성 기능
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/data/model/SearchLocationEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/data/repository/searchLocation/SearchLocationAPIService.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/data/repository/searchLocation/SearchLocationDataSource.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/data/repository/searchLocation/SearchLocationRepository.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/searchlocation/LocationDetailActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/searchlocation/SearchLocationActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/searchlocation/SearchLocationAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/searchlocation/SearchLocationViewModel.kt
  gather-e_android/app/src/main/res/drawable/ic_before.xml
  gather-e_android/app/src/main/res/layout/activity_location_detail.xml
  gather-e_android/app/src/main/res/layout/activity_search_location.xml
  gather-e_android/app/src/main/res/layout/activity_write.xml
Labels: 글작성, 장소 검색 기능

#19 design: [앱 아이콘] 앱 아이콘 변경 - kww
  gather-e_android/app/build.gradle
  gather-e_android/app/src/main/ic_launcher-playstore.png
  gather-e_android/app/src/main/res/drawable/logo.png
  gather-e_android/app/src/main/res/layout/activity_login.xml
  gather-e_android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  gather-e_android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  gather-e_android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  gather-e_android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  gather-e_android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  gather-e_android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  gather-e_android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  gather-e_android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  gather-e_android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  gather-e_android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  gather-e_android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  gather-e_android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  gather-e_android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  gather-e_android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  gather-e_android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  gather-e_android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  gather-e_android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  gather-e_android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  gather-e_android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  gather-e_android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  gather-e_android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  gather-e_android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  gather-e_android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  gather-e_android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  gather-e_android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  gather-e_android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  gather-e_android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  gather-e_android/app/src/main/res/values/ic_launcher_background.xml
Labels: 아이콘, 디자인

#20 [230628] ChatRoom
  gather-e_android/app/build.gradle
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/res/drawable/baseline_image_24.xml
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/item_chat.xml
Labels: 채팅방리스트, 채팅방

#22 [230629] 채팅방 이미지 전송
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/chat/ChatItem.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/activity_login.xml
  gather-e_android/app/src/main/res/layout/item_chat.xml
Labels: 채팅방, 이미지 전송

#23 [230629] 스프링토큰, 카테고리 버튼 동적 생성
  gather-e_android/app/src/main/java/com/kosa/gather_e/MapTestActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/category/CategoryEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/gather/GatherEntity.kt
Labels: 글작성

#24 [230629] 스프링 토큰, 카테고리 버튼 동적 생성
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/category/CategoryEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/gather/GatherEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringInterface.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringRetrofitProvider.kt
  gather-e_android/app/src/main/res/layout/activity_write.xml
  gather-e_spring/src/main/java/com/kosa/gather_e/gathercategory/controller/CategoryController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gathercategory/dao/CategoryDAO.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gathercategory/service/CategoryService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gathercategory/service/CategoryServiceImpl.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gathercategory/vo/CategoryVO.java
  gather-e_spring/src/main/resources/mapper/CategoryMapper.xml
Labels: 글작성

#28 [230628] 자동 로그인
  gather-e_android/app/build.gradle
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/LoginActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/user/JwtToken.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringInterface.kt
  gather-e_android/app/src/main/res/layout/activity_login.xml
  gather-e_spring/src/main/java/com/kosa/gather_e/Application.java
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/controller/AuthController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/auth/dto/Token.java
Labels: 로그인, 로그인 페이지

#29 [230629] 글 작성 후 DB 연동
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/gather/GatherEntity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringInterface.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringRetrofitProvider.kt
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/controller/GatherController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gathercategory/vo/CategoryVO.java
Labels: 글작성

#31 [230629] 자동 로그인 및 마이페이지 구현
  gather-e_android/app/src/main/java/com/kosa/gather_e/LoginActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/repository/spring/SpringRetrofitProvider.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/mypage/MypageFragment.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/mypage/MypageViewModel.kt
  gather-e_android/app/src/main/res/layout/activity_bottom_navigation_var.xml
  gather-e_android/app/src/main/res/layout/fragment_mypage.xml
  gather-e_android/app/src/main/res/values/style.xml
Labels: 로그인 페이지, 마이페이지

#32 [230629] 이미지 전송, 채팅방 UI
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/chat/ChatItem.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/res/drawable/background_talk_mine.xml
  gather-e_android/app/src/main/res/drawable/background_talk_your.xml
  gather-e_android/app/src/main/res/drawable/btn_quit.xml
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/item_chat.xml
  gather-e_android/app/src/main/res/layout/item_chat_mine.xml
  gather-e_android/app/src/main/res/layout/item_chat_your.xml
Labels: 채팅방, 이미지 전송

#35 [230630] 1차 배포를 위한 버그 수정및 api 추가
  gather-e_android/app/src/main/java/com/kosa/gather_e/LoginActivity.kt
  gather-e_android/app/src/main/res/layout/fragment_mypage.xml
  gather-e_spring/src/main/java/com/kosa/gather_e/config/DBConfig.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/dao/GatherDAO.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/service/GatherService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/gather/vo/GatherVO.java
  gather-e_spring/src/main/java/com/kosa/gather_e/test/controller/TestController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/test/dao/TestDAO.java
  gather-e_spring/src/main/java/com/kosa/gather_e/test/service/TestService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/test/vo/TestVO.java
  gather-e_spring/src/main/java/com/kosa/gather_e/user_gather/controller/UserGatherController.java
  gather-e_spring/src/main/java/com/kosa/gather_e/user_gather/dao/UserGatherDAO.java
  gather-e_spring/src/main/java/com/kosa/gather_e/user_gather/service/UserGatherService.java
  gather-e_spring/src/main/java/com/kosa/gather_e/user_gather/service/UserGatherServiceImpl.java
  gather-e_spring/src/main/java/com/kosa/gather_e/user_gather/vo/UserGatherVO.java
  gather-e_spring/src/main/resources/application.yml
  gather-e_spring/src/main/resources/mapper/GatherMapper.xml
  gather-e_spring/src/main/resources/mapper/TestMapper.xml
  gather-e_spring/src/main/resources/mapper/UserGatherMapper.xml
Labels: bug, 배포

#41 [230630]채팅방 목록 UI
  gather-e_android/app/src/main/AndroidManifest.xml
  gather-e_android/app/src/main/java/com/kosa/gather_e/LoginActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/WriteActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/chat/ChatItem.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/model/entity/chat/ChatListItem.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatItemAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatdetail/ChatRoomActivity.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListAdapter.kt
  gather-e_android/app/src/main/java/com/kosa/gather_e/ui/chatlist/ChatListFragment.kt
  gather-e_android/app/src/main/res/drawable/background_talk_mine.xml
  gather-e_android/app/src/main/res/drawable/ic_people.xml
  gather-e_android/app/src/main/res/layout/activity_chat_room.xml
  gather-e_android/app/src/main/res/layout/fragment_chat_list.xml
  gather-e_android/app/src/main/res/layout/item_chat_list.xml
  gather-e_android/app/src/main/res/layout/item_chat_mine.xml
  gather-e_android/app/src/main/res/layout/item_chat_your.xml
Labels: 채팅방리스트, 디자인
